modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="womfix"
version="${mod_version}"
displayName="${mod_name}"
description="${mod_description}"
authors="${mod_author}"

[[dependencies.womfix]]
modId="forge"
mandatory=true
versionRange="[47.4.9,)"
ordering="NONE"
side="BOTH"

[[dependencies.womfix]]
modId="wom"
mandatory=true
versionRange="[20.1.8.5.6,)"
ordering="AFTER"
side="BOTH"

[[dependencies.womfix]]
modId="epicfight"
mandatory=true
versionRange="[20.12.9,)"
ordering="AFTER"
side="BOTH"