modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="womfix"
version="1.0.0"
displayName="WOM Epic Fight Compatibility Fix"
description="Fixes compatibility between Weapons of Miracle and Epic Fight"
authors="YourName"

[[dependencies.womfix]]
modId="forge"
mandatory=true
versionRange="[47.4.9,)"
ordering="NONE"
side="BOTH"

[[dependencies.womfix]]
modId="wom"
mandatory=true
versionRange="[20.1.8.5.6,)"
ordering="AFTER"
side="BOTH"

[[dependencies.womfix]]
modId="epicfight"
mandatory=true
versionRange="[20.12.9,)"
ordering="AFTER"
side="BOTH"
