name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # [span_0](start_span)修复执行权限问题[span_0](end_span)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # **** 新增步骤：为 Gradle 准备本地依赖文件 ****
      - name: Prepare Local Dependency for CI
        run: |
          # 创建 libs 文件夹
          mkdir libs
          # 将根目录下的 JAR 文件移动到 libs/ 文件夹中
          mv WeaponsOfMiracle.jar libs/WeaponsOfMiracle.jar

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: WOMCompatFix-jar
          path: build/libs/*.jar
